//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// FQ01.rc에서 사용되고 있습니다.
//
#define IDC_MYICON                      2
#define IDD_FQ01_DIALOG                 102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_FQ01                        107
#define IDI_SMALL                       108
#define IDC_FQ01                        109
#define IDR_MAINFRAME                   128
#define IDB_INTRO2                      131
#define IDB_INTRO3                      132
#define IDB_INTRO4                      133
#define IDB_INTRO5                      134
#define IDB_INTRO6                      135
#define IDB_INTRO7                      136
#define IDB_INTRO8                      137
#define IDB_INTRO9                      138
#define IDB_INTRO10                     139
#define IDB_INTRO1                      140
#define IDB_BLACK                       145
#define IDB_LOBY                        146
#define IDB_YELLOW                      147
#define IDB_EMPTYLOBY                   148
#define IDB_TEXTBOX1                    150
#define IDB_PNG1                        151
#define IDB_GAMEUI                      152
#define IDB_UIFRAME                     153
#define IDB_SCENEFRAME                  154
#define IDB_FSOLIDER                    156
#define IDB_RSOLIDER                    157
#define IDB_LSOLIDER                    158
#define IDB_test                        159
#define IDB_GENELU_RF                   162
#define IDB_GENELU_LF                   163
#define IDB_GENELU_STAND                165
#define IDB_GENELU_BACK                 166
#define IDB_ORASON_FRONT                167
#define IDB_ORASON_BACK                 168
#define IDB_LAIOS_FRONT                 169
#define IDB_LAIOS_BACK                  170
#define IDB_GABI_FRONT                  171
#define IDB_GABI_BACK                   172
#define IDB_KECK_BRF                    173
#define IDB_KECK_BLF                    174
#define IDB_KECK_FRONT                  175
#define IDB_SARK_FRONT                  176
#define IDB_SARK_BLF                    177
#define IDB_SARK_BRF                    178
#define IDB_MYSOLEN_FRONT               179
#define IDB_MYSOLEN_BACK                180
#define IDB_MAREAM_FRONT                181
#define IDB_MAREAM_BACK                 182
#define IDB_CHAR                        183
#define IDB_SCREENINFRAME               184
#define IDB_KECK                        185
#define IDB_ORASON                      186
#define IDB_LAIOS                       187
#define IDB_OGG                         188
#define IDB_SARK                        189
#define IDB_GABI                        190
#define IDB_MYSOLEN                     191
#define IDB_MAREAM                      192
#define IDB_TOPBGSOLDIER                193
#define IDB_BGSOLDIER                   194
#define IDB_THYHOOT                     195
#define IDB_MOLDRED                     196
#define IDB_MACGAIA                     197
#define IDB_JANIL                       198
#define IDB_GENELU                      199
#define IDB_NPC_TEXT_BOX3               200
#define IDB_THYHOOT_FRONT               201
#define IDB_MACGAIA_FRONT               202
#define IDB_OGG_FRONT                   203
#define IDB_MOLDRED_FRONT               205
#define IDB_JANIL_FRONT                 206
#define IDB_BRSIACASTLE                 207
#define IDB_NPC_TEXT_BOX1               208
#define IDB_NPC_TEXT_BOX2               209
#define IDB_NPC_TEXT_BOX4               211
#define IDB_ARCHBISHOP                  213
#define IDB_SOLDIER3                    214
#define IDB_SOLDIER4                    215
#define IDB_ARES                        216
#define IDB_AERAIN                      217
#define IDB_GON                         218
#define IDB_GONRAD                      218
#define IDB_AEKTER                      219
#define IDB_ARES_STOP                   220
#define IDB_AERAIN_STOP                 221
#define IDB_ARCHBISHOP_STOP             222
#define IDB_GONRAD_STOP                 223
#define IDB_KARION_MEETINGROOM          224
#define IDB_ROCK_SOLDIER                225
#define IDB_SOLDIER2                    226
#define IDB_SOLDIER1                    227
#define IDB_GENERAL                     228
#define IDB_EBRSIACASTLE                230
#define IDB_GENERAL_FACE                231
#define IDB_ANI_INTRO3_FRAME            234
#define IDB_FIELD                       235
#define IDB_SOLDIER5                    236
#define IDB_ARCHER                      237
#define IDB_HORSE_AEKTER                238
#define IDB_HORSE_GENERAL               239
#define IDB_HORSE_SOLDIER               240
#define IDB_KARION_ROYALHOUSE           241
#define IDB_CANDLESTICK                 242
#define IDB_ARMOR                       243
#define IDB_CROW                        244
#define IDB_BARSIAJAIL                  245
#define IDB_GARRARD                     246
#define IDB_BRAZIER                     247
#define IDB_YELLOW_EFFECT               248
#define IDB_TESTINGMAP                  249
#define IDB_GRIFFIN                     250
#define IDB_BAR_JAIL_WINDOW             251
#define IDB_GRATING_CLOSE               253
#define IDB_GRATING_OPEN                254
#define IDB_BARSIACASTLE                255
#define IDB_G_FLAG                      256
#define IDB_RADINKAL                    257
#define IDB_ALFRED                      258
#define IDB_KARION_CASTLE_PART1         259
#define IDB_KARION_CASTLE_ROOM1         260
#define IDB_SMALL_SCREEN                261
#define IDB_KARIONCASTLE_HALL           262
#define IDB_MOVEO                       263
#define IDB_MOVEX                       264
#define IDB_PLAYSCREEN                  265
#define IDB_UnitO                       266
#define IDB_KARIONCASTLE_LAB            268
#define IDB_KARIONCASTLE_KINGROOM       271
#define IDB_KARIONCASTLE_ARESROOM       272
#define IDB_KARIONCASTLE_OUTSIDE        273
#define IDB_KARIONCASTLE_ARMORY         274
#define IDB_KARIONCASTLE_ALTAR          275
#define IDB_PLAYMENU                    277
#define IDB_PLAYMENU_RECORD             280
#define IDB_PLAYMENU_UNITMOVE           281
#define IDB_PLAYMENU_TIMELAPSE          282
#define IDB_PLAYMENU_DIPLOMACY          283
#define IDB_PLAYMENU_INFO               284
#define IDB_PLAYMENU_SEARCH             285
#define IDB_PLAYMENU_ORGANIZATION       286
#define IDB_PLAYMENU_METHOD             287
#define IDB_MAINMENU_BG                 289
#define IDB_ACTION_MENU                 290
#define IDB_PLAYMENU_EXIT               291
#define IDB_ACTION_MENU_ICON            292
#define IDB_ASTARTEST                   293
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        294
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
